# Site settings
title: "tinYield"
description: "Towards sequence traversal optimization and extensibility"
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
